# Generated by Django 5.0.3 on 2024-08-07 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagegallery', '0002_alter_imagegallery_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageGallery',
        ),
    ]
